name: Codacy Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codacy_analysis:
    name: Run Codacy Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.

      - name: Install Codacy Coverage Reporter
        run: |
          curl -Ls https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.3/codacy-coverage-reporter-6.0.3-linux-amd64.tar.gz | tar xz
          sudo mv codacy-coverage-reporter-6.0.3-linux-amd64/codacy-coverage-reporter /usr/local/bin

      - name: Run tests and generate coverage report 
        run: |
          mvn clean test # Ejecuta las pruebas y genera el informe de cobertura con JaCoCo

      - name: Upload coverage to Codacy
        run: |
          codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco-coverage-report.xml -t ${{ secrets.CODACY_PROJECT_TOKEN }}
